name: Built with Eleventy
description: Show off your Eleventy site on the Eleventy documentation
title: "[Built with Eleventy] I built something!"
labels: built-with-eleventy
body:
  - type: markdown
    attributes:
      value: |
        Only the site URL is required. All other fields are optional.
  - type: input
    id: url
    attributes:
      label: Site URL
      description: The home page of the live web site you built. _[parser:url]_
      placeholder: e.g. https://www.zachleat.com/
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please note that site HTML must now include a `<meta name="generator" content="Eleventy">` (or at least `Eleventy` somewhere in the `content` attribute) to be eligible for the Eleventy Leaderboards.
  - type: input
    id: source_url
    attributes:
      label: Source code URL
      description: "Optional: The URL to the **public** repository for the source code for this site. _[parser:url]_"
      placeholder: e.g. https://github.com/zachleat/zachleat.com
    validations:
      required: false
  - type: textarea
    id: authors
    attributes:
      label: "Authors (GitHub usernames)"
      description: "Optional: _Leave this empty if you are the only author._ If you are listing one or more other authors, make sure to include yourself in this list! _[parser:usernames]_"
      placeholder: e.g. @zachleat, @pdehaan
    validations:
      required: false
  - type: input
    id: opencollective
    attributes:
      label: Open Collective Username
      description: "Optional: This marks you as a supporter on the docs. Shown in the URL of your Open Collective profile URL."
      placeholder: e.g. zachleat
    validations:
      required: false
  - type: input
    id: business_url
    attributes:
      label: Super Professional Business Network CTA URL
      description: "Optional: Open Collective Members can be featured on the [Eleventy Super Professional Business Network](https://www.11ty.dev/super-professional-business-network/). Requires a valid Open Collective Username above._[parser:url]_"
      placeholder: e.g. https://www.zachleat.com/
    validations:
      required: false
  - type: input
    id: business_name
    attributes:
      label: Super Professional Business Network Company Name
      description: "Optional: The company name used on the [Eleventy Super Professional Business Network](https://www.11ty.dev/super-professional-business-network/)"
      placeholder: e.g. Zach’s Web Design Emporium
    validations:
      required: false